# Generated by Django 6.1 on 2026-09-02 19:24

import auctions.image_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_is_paid_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionimage',
            name='image',
            field=models.ImageField(upload_to='auction_images/', validators=[auctions.image_validation.validate_auction_image]),
        ),
    ]
