# Generated by Django 6.1 on 2026-09-08 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_product_auction_visibility_moderation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fee_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of PLATFORM_SUCCESS_FEE_PERCENT at checkout (%).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Seller-side commission snapshot (immutable).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='seller_net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross minus platform_fee at checkout (immutable).', max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('fee_rate__isnull', True), models.Q(('fee_rate__gte', 0), ('fee_rate__lte', 100)), _connector='OR'), name='payment_fee_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('platform_fee__isnull', True), ('platform_fee__gte', 0), _connector='OR'), name='payment_platform_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('seller_net_amount__isnull', True), ('seller_net_amount__gte', 0), _connector='OR'), name='payment_seller_net_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('platform_fee__isnull', True), ('platform_fee__lte', models.F('amount')), _connector='OR'), name='payment_platform_fee_lte_amount'),
        ),
    ]
