# Generated by Django 6.1 on 2026-09-22 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_payment_success_fee_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerFulfillmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address_line', models.CharField(blank=True, default='', max_length=255)),
                ('area', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('division', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email')], default='PHONE', max_length=20)),
                ('delivery_note', models.TextField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('completed_step', models.PositiveSmallIntegerField(default=0, help_text='Last successfully saved step (0=None, 1=Personal, 2=Address, 3=Preferences, 4=Submitted)')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner_fulfillment_details', to='auctions.auction')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_fulfillment_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Winner Fulfillment Details',
                'verbose_name_plural': 'Winner Fulfillment Details',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['auction', 'status'], name='win_ful_auction_status_idx'), models.Index(fields=['buyer', 'status'], name='win_ful_buyer_status_idx')],
            },
        ),
    ]
