# Generated by Django 6.1.1 on 2026-09-23 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_winnerfulfillmentdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerDetailsUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, help_text='Immutable snapshot of unlock fee charged (BDT).', max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PAID', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner_details_unlock', to='auctions.auction')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_details_unlocks', to=settings.AUTH_USER_MODEL)),
                ('winner_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unlock_records', to='auctions.winnerfulfillmentdetails')),
            ],
            options={
                'verbose_name': 'Winner Details Unlock',
                'verbose_name_plural': 'Winner Details Unlocks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', 'status'], name='wdu_seller_status_idx'), models.Index(fields=['auction', 'status'], name='wdu_auction_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fee_amount__gte', 0)), name='winner_details_unlock_fee_non_negative'), models.UniqueConstraint(fields=('auction', 'seller'), name='unique_seller_auction_winner_details_unlock')],
            },
        ),
    ]
