# Generated by Django 6.1 on 2026-09-23 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_winner_details_unlock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', '-amount', 'timestamp'], name='bid_auction_amt_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('auction', 'amount'), name='unique_auction_bid_amount'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='bid_amount_positive'),
        ),
    ]
