# Generated by Django 6.1 on 2026-09-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bid_bid_auction_amt_time_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnerdetailsunlock',
            name='bank_tran_id',
            field=models.CharField(blank=True, default='', help_text='Bank transaction ID from gateway.', max_length=100),
        ),
        migrations.AddField(
            model_name='winnerdetailsunlock',
            name='card_type',
            field=models.CharField(blank=True, default='', help_text='Gateway card or channel used (e.g. BKASH, VISA).', max_length=100),
        ),
        migrations.AddField(
            model_name='winnerdetailsunlock',
            name='payment_method',
            field=models.CharField(blank=True, default='SSLCOMMERZ', help_text='Payment gateway or method used (e.g. SSLCOMMERZ, MOCK).', max_length=50),
        ),
        migrations.AddField(
            model_name='winnerdetailsunlock',
            name='val_id',
            field=models.CharField(blank=True, default='', help_text='SSLCommerz validation ID.', max_length=100),
        ),
    ]
