# Generated by Django 6.1.1 on 2026-09-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('OUTBID', 'Outbid'), ('AUCTION_WON', 'Auction Won'), ('AUCTION_LOST', 'Auction Lost'), ('SELLER_NEW_BID', 'Seller New Bid'), ('SELLER_WINNER_DETAILS_READY', 'Seller Winner Details Ready'), ('WINNER_DETAILS_UNLOCKED', 'Winner Details Unlocked'), ('SELLER_WINNER_DETAILS_UPDATED', 'Seller Winner Details Updated')], max_length=32),
        ),
    ]
