# Generated by Django 6.1 on 2026-09-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('OUTBID', 'Outbid'), ('AUCTION_WON', 'Auction Won'), ('AUCTION_LOST', 'Auction Lost'), ('SELLER_NEW_BID', 'Seller New Bid'), ('SELLER_WINNER_DETAILS_READY', 'Seller Winner Details Ready'), ('WINNER_DETAILS_UNLOCKED', 'Winner Details Unlocked'), ('SELLER_WINNER_DETAILS_UPDATED', 'Seller Winner Details Updated'), ('SELLER_VERIFICATION_SUBMITTED', 'Seller Verification Submitted')], max_length=40),
        ),
    ]
