# Generated by Django 6.1 on 2026-09-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', 'id'], 'verbose_name_plural': 'Categories'},
        ),
    ]
